### ISSUE TITLE
App crashes on Movie click

### ISSUE THREAD

**Issue by Indisparte** [Indisparte/CineMates#52]
When selecting a movie, the app crashes with the following error:

```
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.example.cinemates, PID: 21441
    java.lang.NullPointerException: Attempt to invoke virtual method 'int com.example.cinemates.model.data.Collection.hashCode()' on a null object reference
        at com.example.cinemates.model.data.Movie.hashCode(Unknown Source:2)
        at androidx.navigation.NavBackStackEntry.hashCode(NavBackStackEntry.kt:256)
        at java.util.HashMap.hash(HashMap.java:338)
        at java.util.HashMap.put(HashMap.java:611)
        at androidx.navigation.NavController.linkChildToParent(NavController.kt:143)
        at androidx.navigation.NavController.addEntryToBackStack(NavController.kt:1918)
        at androidx.navigation.NavController.addEntryToBackStack$default(NavController.kt:1813)
        at androidx.navigation.NavController$navigate$4.invoke(NavController.kt:1721)
        at androidx.navigation.NavController$navigate$4.invoke(NavController.kt:1719)
        at androidx.navigation.NavController$NavControllerNavigatorState.push(NavController.kt:287)
        at androidx.navigation.fragment.FragmentNavigator.navigate(FragmentNavigator.kt:246)
        at androidx.navigation.fragment.FragmentNavigator.navigate(FragmentNavigator.kt:162)
        at androidx.navigation.NavController.navigateInternal(NavController.kt:260)
        at androidx.navigation.NavController.navigate(NavController.kt:1719)
        at androidx.navigation.NavController.navigate(NavController.kt:1545)
        at androidx.navigation.NavController.navigate(NavController.kt:1472)
        at androidx.navigation.NavController.navigate(NavController.kt:1930)
        at com.example.cinemates.adapter.ItemsRecyclerViewAdapter.navigateToMovieDetails(ItemsRecyclerViewAdapter.kt:176)
        at com.example.cinemates.adapter.ItemsRecyclerViewAdapter.onBindViewHolder$lambda-1(ItemsRecyclerViewAdapter.kt:74)
        at com.example.cinemates.adapter.ItemsRecyclerViewAdapter.$r8$lambda$s5jmOxcUQBSRALnhdqPzMD5vUUw(Unknown Source:0)
        at com.example.cinemates.adapter.ItemsRecyclerViewAdapter$$ExternalSyntheticLambda3.onClick(Unknown Source:4)
        at android.view.View.performClick(View.java:7509)
        at android.view.View.performClickInternal(View.java:7486)
        at android.view.View.access$3600(View.java:841)
        at android.view.View$PerformClick.run(View.java:28709)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:236)
        at android.app.ActivityThread.main(ActivityThread.java:8061)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:656)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:967)

```

**Comment by Indisparte** [comment]
I identified the problem in 2 points:

1. the Movie class' hashCode has not been redefined and there are attributes of the class that, according to the API may be null so it should be reported. The hashCode needs to be redefined by pointing to non-nullable properties.

**Comment by Indisparte** [comment]
I had to remove the Dao class regarding actors because, being still new to Kotlin I have to figure out how to deal with this part later.
