### ISSUE TITLE
Selected movie into Collection dialog crash app

### ISSUE THREAD

**Issue by Indisparte** [Indisparte/CineMates#81]

**Comment by Indisparte** [comment]
When clicking on a movie, the app crashes because it doesn't find a nav controller.

**Logcat**
```
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.example.cinemates, PID: 15128
    java.lang.IllegalStateException: View android.widget.LinearLayout{5d8e9e3 VFE...C.. ...P.... 353,14-664,581} does not have a NavController set
        at androidx.navigation.Navigation.findNavController(Navigation.kt:71)
        at com.example.cinemates.adapter.ItemsRecyclerViewAdapter.navigateToMovieDetails(ItemsRecyclerViewAdapter.kt:188)
        at com.example.cinemates.adapter.ItemsRecyclerViewAdapter.onBindViewHolder$lambda-6$lambda-5(ItemsRecyclerViewAdapter.kt:83)
        at com.example.cinemates.adapter.ItemsRecyclerViewAdapter.$r8$lambda$g0_tNVLo5buEptnFqfxtXakEeDU(Unknown Source:0)
        at com.example.cinemates.adapter.ItemsRecyclerViewAdapter$$ExternalSyntheticLambda3.onClick(Unknown Source:4)
        at android.view.View.performClick(View.java:7509)
        at android.view.View.performClickInternal(View.java:7486)
        at android.view.View.access$3600(View.java:841)
        at android.view.View$PerformClick.run(View.java:28709)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:236)
        at android.app.ActivityThread.main(ActivityThread.java:8061)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:656)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:967)
```

[Problem](https://github.com/Indisparte/CineMates/blob/5538c3d4ba779588846949529ce643b5b52c676b/app/src/main/java/com/example/cinemates/adapter/ItemsRecyclerViewAdapter.kt#L83)

**Comment by Indisparte** [comment]
Same problem with Items in MovieCastFragment, when user click an item app crash
